package main

// registry is the whole dispatched surface, one entry per verb, in name order
// and with each entry's flags in name order. output is filled only where the
// verb prints a JSON document today; errors lists the catalog codes the verb
// can emit today, which is usage wherever parseFlags can fire.
var registry = []verbEntry{
	{
		Name:    "bind",
		Summary: "bind this MasterMind to a runner over a worktree or an existing tree",
		Args:    "[NAME] [--json]",
		Flags: []string{
			"--actor", "--allow-yolo", "--base", "--branch", "--candidate", "--cwd",
			"--feature", "--gate", "--json", "--local", "--mastermind", "--name", "--no-feature", "--no-gate",
			"--rebind", "--regate", "--resume", "--server", "--ticket", "--tier",
			"--timeout", "--worktree",
		},
		Output: "json:BindDoc",
		Exit:   []int{0, 1, 2},
		Errors: []string{"binding_not_found", "conflict", "gate_active", "internal", "policy_refused", "refused", "tier_cap", "usage"},
	},
	{
		Name:    "bugreport",
		Summary: "assemble a local, redacted bug-report bundle and print the gh line",
		Args:    "[--name N] [--round N] [--logs] [--raw] [--out PATH] [--title T] [--body FILE] [--stdout|--json|--gh]",
		Flags:   []string{"--body", "--gh", "--json", "--logs", "--name", "--out", "--raw", "--round", "--stdout", "--title"},
		Output:  "json:bugreport.Doc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"internal", "not_available", "usage"},
	},
	{
		Name:    "chain",
		Summary: "start a chain: build, review and correct across a list of plans",
		Args:    "--name <n> (--plan <file> [--plan <file>...] (--feature <label>|--no-feature) | --resume) [--json]",
		Flags: []string{
			"--base", "--feature", "--gate", "--json", "--mastermind", "--max-corrections", "--name",
			"--no-feature", "--no-gate", "--no-security", "--plan", "--planner-actor", "--regate", "--resume",
			"--reviewer-actor", "--security", "--security-actor", "--server", "--ticket",
		},
		Output: "json:ChainDoc",
		Exit:   []int{0, 1, 2},
		Errors: []string{"binding_not_found", "conflict", "gate_active", "internal", "policy_refused", "refused", "tier_cap", "usage"},
	},
	{
		Name:    "config",
		Summary: "show the actors, the current pick and the candidates",
		Args:    "[--probe [token...]] [--json]",
		Flags:   []string{"--json", "--probe"},
		Output:  "json:ConfigView",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"config_invalid", "internal", "usage"},
	},
	{
		Name:    "config agents",
		Summary: "write the starter agent definitions into the harness config",
		Args:    "[--kind <agy|claude|opencode>] [--agent <name>] [--force] [--dry-run] [--json]",
		Flags:   []string{"--agent", "--dry-run", "--force", "--json", "--kind"},
		Output:  "json:ConfigAgentsDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"internal", "usage"},
	},
	{
		Name:    "config edit",
		Summary: "edit the configuration document in $EDITOR",
		Args:    "",
		Flags:   []string{},
		Exit:    []int{0, 1, 2},
		Errors:  []string{"usage"},
	},
	{
		Name:    "config export",
		Summary: "print the whole configuration document",
		Args:    "[--json]",
		Flags:   []string{"--json"},
		Output:  "json:config document",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"config_invalid", "usage"},
	},
	{
		Name:    "config get",
		Summary: "print the JSON value at a path in the configuration",
		Args:    "<section>[.<key>...] [--json]",
		Flags:   []string{"--json"},
		Output:  "json:the value at the path",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"config_path_not_set", "internal", "usage"},
	},
	{
		Name:    "config import",
		Summary: "import a configuration document from a file or stdin",
		Args:    "<file|-> [--json]",
		Flags:   []string{"--json"},
		Output:  "json:ConfigImportDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"config_invalid", "internal", "usage"},
	},
	{
		Name:    "config init",
		Summary: "write the starter configuration, candidates, policy and actors",
		Args:    "[--force] [--no-agents] [--json]",
		Flags:   []string{"--force", "--json", "--no-agents"},
		Output:  "json:ConfigImportDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"conflict", "internal", "usage"},
	},
	{
		Name:    "config log",
		Summary: "list the configuration revisions, or show one",
		Args:    "[-n N] [--rev N] [--json]",
		Flags:   []string{"--json", "--n", "--rev"},
		Output:  "json:one configuration revision and its changes",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"internal", "revision_not_found", "usage"},
	},
	{
		Name:    "config rollback",
		Summary: "restore an earlier configuration revision",
		Args:    "<rev> [--yes] [-m <message>]",
		Flags:   []string{"--m", "--yes"},
		Exit:    []int{0, 1, 2},
		Errors:  []string{"usage"},
	},
	{
		Name:    "config secret",
		Summary: "store or forget the typesafe and client.key secrets",
		Args:    "set|rm|list",
		Flags:   []string{},
		Exit:    []int{0, 2},
		Errors:  []string{},
	},
	{
		Name:    "config secret list",
		Summary: "print the stored secret names, never their values",
		Args:    "",
		Flags:   []string{"--json"},
		Output:  "json:[]string",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"config_invalid", "internal", "usage"},
	},
	{
		Name:    "config secret rm",
		Summary: "remove a stored secret",
		Args:    "<typesafe|client.key> [--json]",
		Flags:   []string{"--json"},
		Output:  "json:ConfigSecretDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"internal", "usage"},
	},
	{
		Name:    "config secret set",
		Summary: "store a secret read from stdin",
		Args:    "<typesafe|client.key> [--json]",
		Flags:   []string{"--json"},
		Output:  "json:ConfigSecretDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"internal", "usage"},
	},
	{
		Name:    "config server",
		Summary: "this machine's remote-builder identity and its server list",
		Args:    "add|rm|list|key",
		Flags:   []string{},
		Exit:    []int{0, 2},
		Errors:  []string{},
	},
	{
		Name:    "config server add",
		Summary: "record a remote-builder server",
		Args:    "<name> <url> (--fingerprint F | --ca system | --insecure) [--json]",
		Flags:   []string{"--ca", "--fingerprint", "--insecure", "--json"},
		Output:  "json:ConfigServerAddDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"internal", "remote_unreachable", "usage"},
	},
	{
		Name:    "config server key",
		Summary: "print this client's id and the enrolment line a server admin needs",
		Args:    "[--enroll-line] [--json]",
		Flags:   []string{"--enroll-line", "--json"},
		Output:  "json:{id,enroll_line}",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"internal", "usage"},
	},
	{
		Name:    "config server list",
		Summary: "print one row per configured server",
		Args:    "",
		Flags:   []string{"--json"},
		Output:  "json:[]server",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"config_invalid", "internal", "usage"},
	},
	{
		Name:    "config server rm",
		Summary: "forget a configured server",
		Args:    "<name> [--json]",
		Flags:   []string{"--json"},
		Output:  "json:ConfigServerRmDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"conflict", "internal", "server_not_found", "usage"},
	},
	{
		Name:    "config set",
		Summary: "set a configuration section or key to a JSON value",
		Args:    "<section>[.<key>...] <json> [--json]",
		Flags:   []string{"--json"},
		Output:  "json:ConfigWriteDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"config_invalid", "internal", "usage"},
	},
	{
		Name:    "config unset",
		Summary: "remove a configuration section or key",
		Args:    "<section>[.<key>...] [--json]",
		Flags:   []string{"--json"},
		Output:  "json:ConfigWriteDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"config_invalid", "internal", "usage"},
	},
	{
		Name:    "daemon",
		Summary: "run the long-running reconciler",
		Args:    "[--interval D] [--check] [--pprof <path>]",
		Flags:   []string{"--check", "--interval", "--pprof", "--preflight"},
		Exit:    []int{0, 1, 2},
		Errors:  []string{"usage"},
	},
	{
		Name:    "doctor",
		Summary: "preflight check: plugin, daemon, harness binaries, roles, release",
		Args:    "",
		Flags:   []string{"--json"},
		Output:  "json:DoctorDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"config_invalid", "internal", "usage"},
	},
	{
		Name:    "done",
		Summary: "mark a binding done; relaying stops",
		Args:    "[NAME] [--json]",
		Flags:   []string{"--json", "--name", "--pick"},
		Output:  "json:DoneDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"binding_not_found", "conflict", "internal", "refused", "usage"},
	},
	{
		Name:    "gate",
		Summary: "list this machine's gates, gate a provider, or clear one",
		Args:    "[<token>] [--for D] [--reason S] [--json] | --clear <provider|token> | --serve",
		Flags:   []string{"--clear", "--for", "--json", "--reason", "--serve", "--state"},
		Output:  "json:[]GateRow; set/clear: GateDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"internal", "not_available", "policy_refused", "usage"},
	},
	{
		Name:    "help",
		Summary: "print the usage text, or the registry document with --json",
		Args:    "[--json [<verb>]]",
		Flags:   []string{"--json"},
		Output:  "json:registry document",
		Exit:    []int{0, 2},
		Errors:  []string{"usage"},
	},
	{
		Name:    "history",
		Summary: "round history as JSON",
		Args:    "[--binding B] [--since D] [--limit N] [-q QUERY] [--json]",
		Flags: []string{
			"--binding", "--by", "--feature", "--here", "--json", "--limit",
			"--mastermind", "--q", "--rows", "--since", "--ticket",
		},
		Output: "json:[]RoundRow",
		Exit:   []int{0, 1, 2},
		Errors: []string{"internal", "usage"},
	},
	{
		Name:    "mastermind",
		Summary: "register this MasterMind, and list, rename or forget records",
		Args:    "init|notice|enable|disable|reset|guide|list|rename|forget",
		Flags:   []string{},
		Exit:    []int{0, 2},
		Errors:  []string{},
	},
	{
		Name:    "mastermind disable",
		Summary: "withdraw consent for this session or repository",
		Args:    "[--repo] [--kind K --session S] [--json]",
		Flags:   []string{"--json", "--kind", "--repo", "--session"},
		Output:  "json:MasterMindDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"conflict", "internal", "refused", "usage"},
	},
	{
		Name:    "mastermind enable",
		Summary: "consent this session or repository to relevo",
		Args:    "[--repo] [--kind K --session S] [--json]",
		Flags:   []string{"--json", "--kind", "--repo", "--session"},
		Output:  "json:MasterMindDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"conflict", "internal", "refused", "usage"},
	},
	{
		Name:    "mastermind forget",
		Summary: "forget a MasterMind record",
		Args:    "<id|name> [--json]",
		Flags:   []string{"--json"},
		Output:  "json:MasterMindDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"conflict", "internal", "mastermind_not_found", "usage"},
	},
	{
		Name:    "mastermind guide",
		Summary: "print the MasterMind guide, or this session's consent document",
		Args:    "[--cwd DIR] [--kind K --session S] [--json]",
		Flags:   []string{"--cwd", "--json", "--kind", "--session"},
		Output:  "json:the consent document {\"state\",\"text\",\"repo\",\"id\",\"name\"}",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"internal", "usage"},
	},
	{
		Name:    "mastermind init",
		Summary: "register this MasterMind, or re-attach an existing record",
		Args:    "[--name N] [--kind K --session S] [--hook claude] [--json]",
		Flags:   []string{"--hook", "--json", "--kind", "--name", "--session"},
		Output:  "json:MasterMindDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"conflict", "internal", "refused", "usage"},
	},
	{
		Name:    "mastermind list",
		Summary: "list the MasterMind records",
		Args:    "[--json]",
		Flags:   []string{"--json"},
		Output:  "json:[]a record per MasterMind",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"internal", "usage"},
	},
	{
		Name:    "mastermind notice",
		Summary: "the UserPromptSubmit hook that reports a status change",
		Args:    "--hook claude",
		Flags:   []string{"--hook"},
		Exit:    []int{0, 1, 2},
		Errors:  []string{"usage"},
	},
	{
		Name:    "mastermind rename",
		Summary: "rename a MasterMind record",
		Args:    "<id|name> <new-name> [--json]",
		Flags:   []string{"--json"},
		Output:  "json:MasterMindRenameDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"conflict", "internal", "mastermind_not_found", "usage"},
	},
	{
		Name:    "mastermind reset",
		Summary: "forget this session's or repository's consent answer",
		Args:    "[--kind K --session S] [--json]",
		Flags:   []string{"--json", "--kind", "--session"},
		Output:  "json:MasterMindDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"internal", "refused", "usage"},
	},
	{
		Name:    "mcp",
		Summary: "run an MCP server over stdio for a Claude Code MasterMind pane",
		Args:    "[--mode channel|tools|auto]",
		Flags:   []string{"--interval", "--kind", "--mastermind", "--mode"},
		Exit:    []int{0, 1, 2},
		Errors:  []string{"usage"},
	},
	{
		Name:    "send",
		Summary: "stage a plan file as the current round and start the runner",
		Args:    "--file <plan> [NAME] [--json]",
		Flags: []string{
			"--allow-yolo", "--candidate", "--dry-run", "--file", "--force", "--json",
			"--name", "--no-verify", "--regate", "--tier", "--verify",
		},
		Output: "json:SendDoc; --dry-run: relevo.DryRun",
		Exit:   []int{0, 1, 2},
		Errors: []string{"binding_not_found", "conflict", "gate_active", "internal", "policy_refused", "refused", "tier_cap", "usage"},
	},
	{
		Name:    "serve",
		Summary: "run the remote-builder server (listener + daemon)",
		Args:    "[--listen :7777] [--state <dir>] [--interval 2s]",
		Flags: []string{
			"--insecure-http", "--interval", "--listen", "--max-builders",
			"--max-bundle-bytes", "--public-host", "--state",
		},
		Exit:   []int{0, 1, 2},
		Errors: []string{"usage"},
	},
	{
		Name:    "serve clients",
		Summary: "list the enrolled clients",
		Args:    "[--state <dir>]",
		Flags:   []string{"--json", "--state"},
		Output:  "json:[]client",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"internal", "not_available", "usage"},
	},
	{
		Name:    "serve enroll",
		Summary: "enroll a client's public key",
		Args:    "--label <label> --key \"<ed25519 line>\" [--state <dir>] [--json]",
		Flags:   []string{"--json", "--key", "--label", "--state"},
		Output:  "json:ServeEnrollDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"conflict", "internal", "usage"},
	},
	{
		Name:    "serve fingerprint",
		Summary: "print the server certificate's fingerprint",
		Args:    "[--state <dir>]",
		Flags:   []string{"--json", "--state"},
		Output:  "json:{\"fingerprint\"}",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"internal", "not_available", "usage"},
	},
	{
		Name:    "serve gc",
		Summary: "unbind bindings abandoned for longer than a threshold",
		Args:    "--abandoned <duration> [--dry-run] [--state <dir>] [--json]",
		Flags:   []string{"--abandoned", "--dry-run", "--json", "--state"},
		Output:  "json:ServeGCDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"internal", "not_available", "usage"},
	},
	{
		Name:    "serve init",
		Summary: "initialise the serve state root and its certificate",
		Args:    "[--host <name>]... [--state <dir>] [--json]",
		Flags:   []string{"--host", "--json", "--state"},
		Output:  "json:ServeInitDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"internal", "usage"},
	},
	{
		Name:    "serve revoke",
		Summary: "revoke an enrolled client",
		Args:    "<id> [--state <dir>] [--json]",
		Flags:   []string{"--json", "--state"},
		Output:  "json:ServeRevokeDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"client_not_found", "internal", "not_available", "usage"},
	},
	{
		Name:    "serve status",
		Summary: "print the census as JSON",
		Args:    "[--json] [--state <dir>]",
		Flags:   []string{"--json", "--state"},
		Output:  "json:census",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"internal", "not_available", "usage"},
	},
	{
		Name:    "serve ui",
		Summary: "watch the server's queue in a terminal",
		Args:    "[--state <dir>] [--interval 2s]",
		Flags:   []string{"--interval", "--state"},
		Exit:    []int{0, 1, 2},
		Errors:  []string{"usage"},
	},
	{
		Name:    "serve unbind",
		Summary: "unbind one of an owner's bindings on the server host",
		Args:    "--owner <label|id> <name> [--state <dir>] [--force] [--json]",
		Flags:   []string{"--force", "--json", "--owner", "--state"},
		Output:  "json:ServeUnbindDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"binding_not_found", "client_not_found", "conflict", "internal", "not_available", "usage"},
	},
	{
		Name:    "show",
		Summary: "one round's plan, report, diff, drift, gate, findings, log or transcript",
		Args:    "[NAME] [--round N] [--diff [--stat|--anchors]] [--log [--follow --after N]] [--trace] [--json] [--peek]",
		Flags: []string{
			"--after", "--anchors", "--artifact", "--artifacts", "--diff", "--drift",
			"--findings", "--follow", "--gate", "--json", "--log", "--output",
			"--owner", "--peek", "--prompt", "--report", "--round", "--stat",
			"--state", "--trace", "--transcript",
		},
		Output: "json:ShowResult; --log prints NDJSON events",
		Exit:   []int{0, 1, 2},
		Errors: []string{"artifact_not_found", "binding_not_found", "internal", "round_not_found", "usage"},
	},
	{
		Name:    "status",
		Summary: "one row per binding: round, state, live pane status, what is pending",
		Args:    "[--all] [--name NAME] [--line] [--json]",
		Flags:   []string{"--all", "--json", "--line", "--name"},
		Output:  "json:view.Report; --line: json:view.StatusLineDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"binding_not_found", "internal", "usage"},
	},
	{
		Name:    "stop",
		Summary: "kill the runner process and close its round unless a report is on disk",
		Args:    "[NAME] [--json]",
		Flags:   []string{"--json", "--name"},
		Output:  "json:StopDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"binding_not_found", "internal", "usage"},
	},
	{
		Name:    "ui",
		Summary: "the cockpit: :fleet, :rounds [query], :round <binding> [N]",
		Args:    "[:view [args]]",
		Flags:   []string{"--interval"},
		Exit:    []int{0, 1, 2},
		Errors:  []string{"usage"},
	},
	{
		Name:    "unbind",
		Summary: "forget a binding, deleting or archiving its directory",
		Args:    "[NAME] [--done] [--delete] [--dry-run] [--json]",
		Flags: []string{
			"--all-masterminds", "--archive", "--delete", "--done", "--dry-run",
			"--json", "--mastermind", "--name", "--pick", "--sweep",
		},
		Output: "json:UnbindDoc; --done: gcDoc; --sweep: sweepDoc",
		Exit:   []int{0, 1, 2},
		Errors: []string{"binding_not_found", "conflict", "internal", "refused", "usage"},
	},
	{
		Name:    "update",
		Summary: "replace this release binary with the latest release, checksum-verified",
		Args:    "[--check] [--to vX.Y.Z] [--release] [--json]",
		Flags:   []string{"--check", "--json", "--release", "--to"},
		Output:  "json:updateDoc",
		Exit:    []int{0, 1, 2},
		Errors:  []string{"internal", "refused", "remote_unreachable", "usage"},
	},
	{
		Name:    "version",
		Summary: "print the relevo version",
		Args:    "",
		Flags:   []string{"--json"},
		Output:  "json:{\"version\"}",
		Exit:    []int{0, 2},
		Errors:  []string{"usage"},
	},
	{
		Name:    "wait",
		Summary: "block until a round closes or needs you, then print the pending report",
		Args:    "[NAME] [--any] [--round N] [--peek] [--timeout D] [--json]",
		Flags:   []string{"--any", "--json", "--name", "--peek", "--round", "--timeout"},
		Output:  "json:WaitDoc",
		Exit:    []int{0, 2, 3, 4, 5, 6, 124},
		Errors:  []string{"binding_not_found", "internal", "round_not_found", "usage"},
	},
}
